[build]
command = "cd planilha-financeira && npm ci && npm run build"
publish = "planilha-financeira/dist/planilha-financeira/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
NODE_VERSION = "18"

