[build]
  command = "cd planilha-financeira && npm install && npm run build"
  publish = "planilha-financeira/dist/planilha-financeira/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

