[build]
command = "npm run build"
publish = "dist/planilha-financeira/browser"

[build.environment]
NETLIFY_SKIP_ANGULAR_RUNTIME = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200